# Generated by Django 4.2.5 on 2023-09-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("AV", "Доступен"), ("UV", "Недоступен")],
                        default="AV",
                        max_length=2,
                        verbose_name="Статус продукта",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название продукта"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Слаг"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание продукта"
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Вес"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на оригинальный товар",
                    ),
                ),
                (
                    "price",
                    models.PositiveBigIntegerField(
                        verbose_name="Актуальная цена продукта"
                    ),
                ),
                (
                    "old_price",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Старая цена продукта"
                    ),
                ),
                (
                    "count",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Количество продукта"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
