# Generated by Django 4.2.5 on 2023-09-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product",
            new_name="name",
        ),
    ]
